#!/usr/bin/env bash

# source config
source $HOME/.config/golazo/golazo.conf

# get random code and apply it to pre
random_color () {
    size=${#colors[@]}
    index=$(($RANDOM % $size))
    echo "${colors[$index]}${pre}\e[0m"
}

# things to be fetched
declare -A fetch=(
    [user]="$USER"
    [host]="$(cat /etc/hostname)"
    [uptime]="$(uptime | awk '{print $3}' | sed 's/:/h / ; s/,/m/')"
    [kernel]="$(awk '{print $3}' /proc/version)"
    [distro]="$(sed -n 's/^PRETTY_NAME="//p' /etc/os-release | sed 's/"//')"
    [shell]="$(basename $SHELL)"
    [de]="$XDG_CURRENT_DESKTOP"
    [terminal]="$TERM"
    [editor]="$EDITOR"
    [root]="$(df -Th / | tail -n 1 | awk '{print $6}'), $(df -Th / | tail -n 1 | awk '{print $2}')"
    [ip]="$(host myip.opendns.com resolver1.opendns.com | tail -n 1 | awk '{print $4}')"
    [battery]="$(cat /sys/class/power_supply/BAT0/capacity)%"
    [cpu]="$(sed -n 5p /proc/cpuinfo | cut -d: -f2)"
    [ram]="$(free -h | sed -n 2p | awk '{print $3}') / $(free -h | sed -n 2p | awk '{print $2}')"
    [swap]="$(free -h | sed -n 3p | awk '{print $3}') / $(free -h | sed -n 3p | awk '{print $2}')"
    [display]="$(xrandr | grep '*' | awk '{print $1}'), $(xrandr | grep '*' | awk '{print $2}' | sed 's/*/Hz/ ; s/+//')"
)

main () {
    for info in "${order[@]}"; do
        echo -e "$(random_color) \e[0;1;3m$info\e[0m${sep}${fetch[$info]}"
    done
}

main
